#!/bin/bash rundot.sh
#
# This script uses graphviz/dot to create a .png of a directed graph 
#	representing the property ownership/transfers within Lockridge.
#
# Basis:
#	I reconstructed this from a poster of founders and members shown
#	to me by Bryan and Joanna Bomberg.
#
# Problems:
#	The original poster was more about community than property.  It
#	tries to list all people who have entered the community, but is
#	incomplete on transfers:
#	  - a few people are mentioned without lots, perhaps because
#	    those lots had not yet been given numbers.
#	  - a few sellers are mentioned who were never listed as
#	    having purchased the property.
#	  - the poster ends in 2013, but I was able to consult Orange
#	    county property records to find the most recent transfers.
#
# Validation vs current membership:
#	1. all people shown as current owners appear on the current
#	   membership spreadhseet.
#	2. no body who is shown as having sold their property is
#	   listed in the current spreadhseet, except for DeBoer
#	   who still lives in the area (w/Godar)
#	
digraph members {
	// transfers run from left to right
	rankdir=LR;
	
	// general parameters for all nodes
	node [ fixedsize = true, height = 0.7, fontsize = 10 ];

	// nodes for the lots (in inverse order of date of 1st transfer)
	node [ shape = doublecircle color = darkgreen ];
	  //	parcel		   address		mshp
	  //	------		   -------		----
	  	"H26"		// 1000/1001 Wilbea Rd	H26
		"West 10"	// 3218 Other Duck ln	H24
		"West 1"	// 3219 Tipi Ln		H15
		"East 1"	// 5500 Lockridge Rd	H2
		"H21"		// 3200 Wined Elm Ln	H21
		"East 12"	// 5617 Community Dr	H11
		"West 7"	// 3207 Winged Elm Ln	H19
		"East 11"	// 5619 Community Dr	H10
		"West 5"	// 3222 Tipi Ln		H14
		"West 6"	// 3221 Winged Elm Ln	H22
		"West 9"	// 3219 Other Duck Ln	H23
		"West 8"	// 3201 Winged Elm Ln	H20
		"West 4"	// 3201 Tipi Ln		H18
		"West 2"	// 3211 Tipi Ln		H16
		"East 2"	// 5506 Lockridge Rd	H3
		"West 3"	// 3205 Tipi Ln		H17
		"East 13"	// 5728 Turkey Farm Rd	H13
		"East 10"	// 5621 Community Dr	H9
		"East 14"	// 5622 Turkey Farm Rd	H12
		"East 6/7"	// 5616 Community Dr	H6
		"East 15"	// 5518 Turkey Farm Rd	H1
		"East 9"	// 5623 Community Dr	H8
		"East 8"	// 5622 Community Dr	H7
		"East 5"	// 5602 Lockridge Rd	H5
		"East 3/4"	// 5520 Lockridge Rd?	H4

	// nodes for the original founders
	node [ shape = circle height = 1.0 color = green ];
		"Martha+Bob\nGwyn"
		"David\nMcFadden"
		"Kathy+Sandy\nSeaton"
		"Carolyn+Karl\nOstrom"
		"Val+Skip\nMcGaughay"
	// founders listed in 1972 who never acquired any property
	//	"Thelma/John\nLennon"
	//	"Murrells"
	//	"Stece\nPutman"

	// nodes for pre-1980 members
	node [ shape = circle height = 1.0 color = green ];
		"Jayne+Bryan\nBomberg"	// Jayne & Brian, Joanna
		"Ron\nBenson"
		"R.Dean\nDeBoer"
		"George\nFilonowicz"
		"Bob\nFleishman"
		"Walker\nLinda\nHagans"
		"Svea+Arnie\nKatz"
		"Carol+Bill\nKehrer"
		"Patty\nKirkley"
		"Patty\nKirkley "
		"Shirley+John\nMcConahay"
		"Barbara+Lee\nPederson"
		"Carol Stack\nKen\nWilliamson"
		"Bill\nTriplett"
		"Deborah\nShaw"
		"Sara+Jeff\nRoseman"

	// nodes for later members are in a lighter color
	node [ shape = circle height = 1.0 color = aqua ];
		"Erika+Josh\nAlexander"
		"Robert\nBates"
		"Marni+Steve\nBeatrous"
		"Sallye Coyle\nTed Hall"
		"Sally DeGraff\nBruce\nWinterhalter"
		"Daniel\nDel Corso"
		"David\nDelany"
		"Godi\nGodar"
		"Chris+Lissa\nGotwals"
		"Kit\nGruelle"
		"Albert\nHardy"
		"Max+Marsha\nJohnson"
		"Jennifer\nKampe"
		"Mark\nLynnette\nKampe"
		"Mary+Fritz\nKlein"
		"Christine\nKrohn"
		"Deborah\nLawrence"
		"Coleen+Gil\nLibby"
		"Chris Lucia\nAlyssa\nBernanke"
		"Jane+Roger\nMadison"
		"Martha\nHeinrich\nMalling"
		"Cheryl\nMarcus\nRoy\nSchonberg"
		"William\nMatthews"
		"Sabine+Mark\nMead"
		"Tricia\nPatterson"
		"Bepi+Forest\nPinner"
		"Cheryl\nMichael\nPope"
		"Helen+David\nRogers"
		"Sara Rubin\nJim Blose"
		"Ken\nSchonwalter"
		"Elizabeth\nTurner"
		"Wells\n(Chrysalis)"
		"Roger\nWindsor"

	// original purchases
	"East 15" -> "Val+Skip\nMcGaughay"			[ label = "1972", fontsize = 10 ];
	"East 9" -> "Kathy+Sandy\nSeaton"			[ label = "1972", fontsize = 10 ];
	"East 8" -> "David\nMcFadden"				[ label = "1972", fontsize = 10 ];
	"East 5" -> "Martha+Bob\nGwyn"				[ label = "1972", fontsize = 10 ];
	"East 3/4" -> "Carolyn+Karl\nOstrom"			[ label = "1972", fontsize = 10 ];

	// subsequent sales from top-left page
	"East 6/7" -> "Jayne+Bryan\nBomberg"			[ label = "1973", fontsize = 10 ];
	"East 14" -> "Carol+Bill\nKehrer"			[ label = "1973", fontsize = 10 ];
	"East 10" -> "R.Dean\nDeBoer"				[ label = "1975", fontsize = 10 ];
	"East 13" -> "Walker\nLinda\nHagans"			[ label = "1975", fontsize = 10 ];
	"Val+Skip\nMcGaughay" -> "Barbara+Lee\nPederson"	[ label = "1975", fontsize = 10 ];
	"Kathy+Sandy\nSeaton" -> "Ron\nBenson"			[ label = "1975", fontsize = 10 ];
	"West 3" -> "Shirley+John\nMcConahay"			[ label = "1976", fontsize = 10 ];
	"East 2" -> "Carol Stack\nKen\nWilliamson"		[ label = "1980", fontsize = 10 ];
	"West 2" -> "Bill\nTriplett"				[ label = "1977", fontsize = 10 ];
	"West 4" -> "George\nFilonowicz"			[ label = "1979", fontsize = 10 ];

	// subsequent sales from bottom-left page
	"West 8" -> "Svea+Arnie\nKatz"				[ label = "1978", fontsize = 10 ];
	"West 9" -> "Sara+Jeff\nRoseman"			[ label = "1978", fontsize = 10 ];
	"West 6" -> "Deborah\nShaw"				[ label = "1978", fontsize = 10 ];
	"East 11" -> "Bob\nFleishman"				[ label = "1978", fontsize = 10 ];
	"East 12" -> "Bob\nFleishman "				[ label = "1978", fontsize = 10 ];
	"West 5" -> "Patty\nKirkley"				[ label = "1978", fontsize = 10 ];
	"Barbara+Lee\nPederson" -> "Sara Rubin\nJim Blose"	[ label = "1979", fontsize = 10 ];
	"H21" -> "Martha\nHeinrich\nMalling"			[ label = "1980", fontsize = 10 ];
	"Patty\nKirkley" -> "Helen+David\nRogers"		[ label = "1981", fontsize = 10 ];
	"Coleen+Gil\nLibby" -> "Bepi+Forest\nPinner"		[ label = "1982", fontsize = 10 ];
	"Bob\nFleishman" -> "Albert\nHardy"			[ label = "1983", fontsize = 10 ];
	"East 1" -> "Marni+Steve\nBeatrous"			[ label = "1984", fontsize = 10 ];

	// subsequent sales from top-right page
	"George\nFilonowicz" -> "Cheryl\nMarcus\nRoy\nSchonberg" [ label = "1988", fontsize = 10 ];
	"R.Dean\nDeBoer" -> "Daniel\nDel Corso"			[ label = "1987", fontsize = 10 ];
	"Walker\nLinda\nHagans" -> "Jane+Roger\nMadison"	[ label = "1988", fontsize = 10 ];
	"William\nMatthews" -> "Tricia\nPatterson"		[ label = "1990", fontsize = 10 ];
	"Robert\nBates" -> "Sallye Coyle\nTed Hall"		[ label = "1993", fontsize = 10 ];
	"Bob\nFleishman " -> "Mary+Fritz\nKlein"		[ label = "1994", fontsize = 10 ];

	// subsequent sales from bottom-right page
	"Patty\nKirkley " -> "Erika+Josh\nAlexander"		[ label = "1997", fontsize = 10 ];
	"Sally DeGraff\nBruce\nWinterhalter" -> "Sabine+Mark\nMead"	[ label = "1997", fontsize = 10 ];
	"Roger\nWindsor" -> "Deborah\nLawrence"			[ label = "2008", fontsize = 10 ];
	"Max+Marsha\nJohnson" -> "Christine\nKrohn" 		[ label = "2013", fontsize = 10 ];

	// added w/info from NC property records or direct knowledge
	"Carolyn+Karl\nOstrom" -> "David\nDelany"		[ label = "1977" fontsize = 10 ];
	"West 7" -> "Patty\nKirkley "				[ label = "1980", fontsize = 10 ];
	"West 1" -> "William\nMatthews"				[ label = "1980", fontsize = 10 ];
	"David\nDelany" -> "Robert\nBates"			[ label = "1986", fontsize = 10 ];
	"Carol+Bill\nKehrer" -> "Elizabeth\nTurner"		[ label = "1985", fontsize = 10 ];
	"Elizabeth\nTurner" -> "Kit\nGruelle"			[ label = "1987", fontsize = 10 ];
	"H26" -> "Godi\nGodar"					[ label = "1988", fontsize = 10 ];
	"Daniel\nDel Corso" -> "Cheryl\nMichael\nPope"		[ label = "1999", fontsize = 10 ];
	"Martha+Bob\nGwyn" -> "Ken\nSchonwalter"		[ label = "1999", fontsize = 10 ];
	"Ken\nSchonwalter" -> "Roger\nWindsor"			[ label = "1999", fontsize = 10 ];
	"Sara Rubin\nJim Blose" -> "Chris+Lissa\nGotwals"	[ label = "2014", fontsize = 10 ];
	"Sallye Coyle\nTed Hall" -> "Chris Lucia\nAlyssa\nBernanke" [ label = "2020", fontsize = 10 ];
	"Kit\nGruelle" -> "Max+Marsha\nJohnson"			[ label = "1988", fontsize = 10 ];
	"Sabine+Mark\nMead" -> "Jennifer\nKampe"		[ label = "2022", fontsize = 10 ];
	"Bill\nTriplett" -> "Mark\nLynnette\nKampe"		[ label = "2025", fontsize = 10 ];
	"West 10" -> "Wells\n(Chrysalis)"			[ label = "1979", fontsize = 10 ];
	"Wells\n(Chrysalis)" -> "Sally DeGraff\nBruce\nWinterhalter" [ label = "1981" fontsize = 10 ];
	"David\nMcFadden" -> "Coleen+Gil\nLibby"		[ label = "1978", fontsize = 10 ];
}
