#!/bin/bash
#	a single command to start up my standard desktop
LOG=$HOME/desktop.log	# where to capture stardup stdout/stderr
DELAY=2			# wait for window to be created

# default configuration
WINDOWS="Home"
Home_TABS="https://calendar.google.com/calendar/u/0/r/month"
Home_DIR="/home/markk"
WIDE=710	# xterm window width
LONG=1600	# xterm length on vertical screen
SHORT=1200	# xterm length on horizontal screen
RIGHT=1040	# pixel offset of RHS screen
RWID=1920	# width of RHS screen

if [ -r $HOME/.desktop ]
then
    echo using desktop configuration from $HOME/.desktop >> $LOG
    . $HOME/.desktop
fi

# compute browser window size/position for LHS browsers
B_WIDTH=$((95 * $RIGHT / 100))		# don't have full width on left
B_LENGTH=$((8 * $LONG / 10))		# shorter than the xterm
B_SIZE="--window-size=$B_WIDTH,$B_LENGTH"
B_DOWN=2				# avoid full screen
B_LEFT=2				# avoid app menu
B_POS="--window-position=$B_LEFT,$B_DOWN"

date > $LOG
WS=0

if [ -z "$1" ]
then
   run () { eval $1; }
else
   run () { echo $1; }
fi

# per every window commands
for t in $WINDOWS
do
    echo "initializing workspace $t ($WS)"
    run "wmctrl -s $WS"
    sleep $DELAY

    
    # figure out what tabs and directory to use
    TABS=`eval echo "$""$t""_TABS"`
    DIR=`eval echo "$""$t""_DIR"`
    
    echo "... starting UXterms for $WS: $t in $DIR"
    cd $DIR
    if [ $WS -ne 0 ]
    then
    	# this was created manually in WS0
        run "uxterm -title $t-lhs &"
    else
	# title the xterm in which we are runnin
    	echo -ne '\033]2;Home-lhs\007'
    fi
    run "uxterm -title $t-rhs &"

    # see if this window has defined browser tabs
    if [ -n "$TABS" ]
    then
	echo "... starting Chrome window for $t"
	run "google-chrome-stable --new-window $B_SIZE $B_POS $TABS >>$LOG 2>>$LOG &"
    fi

    # ... placing and sizing XTERMs for $WS: $t
    sleep $DELAY

    if [ $WS -ne 0 ]
    then
	# this was created manually in WS0
	run "wmctrl -r $t-lhs -e 0,0,0,$WIDE,$LONG"
    fi
    run "wmctrl -r $t-rhs -e 0,$RIGHT,0,$WIDE,$SHORT"

    let "WS = $WS + 1"
done

# additional windows for the Home workspace
WS=0
t=`echo $WINDOWS | cut -d\  -f1`
echo "Additional windows for workspace $t ($WS)"
DIR=`eval echo "$""$t""_DIR"`
cd $DIR
run "wmctrl -s $WS"
sleep $DELAY
for a in $HOME_CMDS
do
   echo "... starting $a for $t"
   if [ "$a" = "diary" ]
   then
   	run diary
	# put it at the right edge of the RHS screen
	W=$(($RWID * 2 / 7))
	H=$(($SHORT * 3 / 4 ))
	X=$(($RIGHT + $RWID - $W))
	Y=5		# Y=0 gets full size
	sleep 1
   	wmctrl -r GVIM -e 0,$X,$Y,$W,$H
   elif [ "$a" = "thunderbird" ]
   then
	# can I figure out how to size/position this
   	run "thunderbird &"
   else
   	run "$a >> $LOG 2>> $LOG &"
   fi
   # note: I have not figured out how to reposition these windows
done
