#!/bin/bash

HEIGHT=55	# usually on horizontal monitor
WIDTH=72	# don't take up too much room
GEOMETRY="-geometry $WIDTH"x"$HEIGHT"

EDITOR=/usr/bin/gvim

MONTH=`date "+%b%y"`
YEAR=`date "+%Y"`
PATH="$HOME/Diaries/$YEAR"
FILE="$MONTH.txt"

if [ -f $PATH/$FILE ]
then
    echo using existing $FILE in $PATH
else
    echo creating new $FILE in $PATH
fi

( cd $PATH; $EDITOR $GEOMETRY $MONTH.txt ) &
